In [ ]:
# FORMAT FOR TIME BASED EDA
# QUESTION
### OBJECTIVE
### CODE
### VISUALISATION
### OBSERVATION
### INSIGHTS
# GOING TO USE AVERAGE HOURLY RIDERSHIP = MEAN OF TOTAL RIDERSHIP FOR EACH HOUR
# creating reusable variables

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# plot settings
plt.style.use("default")
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['axes.grid'] = True

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.precision", 2)

df=pd.read_csv("/Users/shivaya/Desktop/Research/DelhiMetroResearch/DataProcessed/metro_master.csv")

In [4]:
print(df.shape)
df.head(5)
df.sample(5)

(1872465, 9)

,businessday,linename,sitename,station name,station code,hour,count,month,direction
1054348,2024-12-30,LINE05,Nangloi,Nangloi,NNOI,18,707,December,Entry
656769,2024-11-18,LINE06,Jama Masjid,Jama Masjid,JAMD,7,129,November,Entry
1329708,2025-01-02,LINE03,Sector-61 Noida,Sector - 61 Noida,SSON,13,178,January,Entry
338000,2024-10-21,LINE06,Sarai,Sarai,SRAI,7,658,October,Entry
297961,2024-09-12,LINE03,Subhash Nagar,Subhash Nagar,SN,23,213,September,Exit

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1872465 entries, 0 to 1872464
Data columns (total 9 columns):
 #   Column        Dtype
---  ------        -----
 0   businessday   str
 1   linename      str
 2   sitename      str
 3   station name  str
 4   station code  str
 5   hour          int64
 6   count         int64
 7   month         str
 8   direction     str
dtypes: int64(2), str(7)
memory usage: 232.3 MB

In [6]:
df.columns.tolist()

['businessday',
 'linename',
 'sitename',
 'station name',
 'station code',
 'hour',
 'count',
 'month',
 'direction']

In [9]:
df.info()
df["direction"].value_counts()

<class 'pandas.DataFrame'>
RangeIndex: 1872465 entries, 0 to 1872464
Data columns (total 9 columns):
 #   Column        Dtype
---  ------        -----
 0   businessday   str
 1   linename      str
 2   sitename      str
 3   station name  str
 4   station code  str
 5   hour          int64
 6   count         int64
 7   month         str
 8   direction     str
dtypes: int64(2), str(7)
memory usage: 232.3 MB

direction
Entry    936243
Exit     936222
Name: count, dtype: int64

In [10]:
# Check missing values in columns required for time-based EDA
required_columns = [
    "businessday",
    "month",
    "hour",
    "direction",
    "count"
]

df[required_columns].isnull().sum()

businessday    0
month          0
hour           0
direction      0
count          0
dtype: int64

In [11]:
missing = pd.DataFrame({
    "Missing Values": df[required_columns].isnull().sum(),
    "Percentage (%)": (
        df[required_columns].isnull().mean() * 100
    ).round(2)
})

missing

             Missing Values  Percentage (%)
businessday               0             0.0
month                     0             0.0
hour                      0             0.0
direction                 0             0.0
count                     0             0.0

In [12]:
daily_hourly = (
    df.groupby(
        ["businessday", "month", "hour", "direction"],
        as_index=False 
    )["count"].sum()
)

In [14]:
daily_hourly.head()
daily_hourly.shape

(7602, 5)

In [15]:
print(df["month"].unique())

<ArrowStringArray>
['September', 'October', 'November', 'December', 'January', 'February']
Length: 6, dtype: str

In [16]:
daily_hourly.head(10)

  businessday      month  hour direction  count
0  2024-09-01  September     0     Entry     56
1  2024-09-01  September     0      Exit   4456
2  2024-09-01  September     4     Entry      1
3  2024-09-01  September     4      Exit      0
4  2024-09-01  September     5     Entry  10655
5  2024-09-01  September     5      Exit    393
6  2024-09-01  September     6     Entry  42633
7  2024-09-01  September     6      Exit  14199
8  2024-09-01  September     7     Entry  70072
9  2024-09-01  September     7      Exit  50411

In [17]:
daily_hourly.describe()

          hour      count
count  7602.00    7602.00
mean     12.86  141915.52
std       6.32   99058.04
min       0.00       0.00
25%       8.00   46126.75
50%      13.00  159450.50
75%      18.00  194816.75
max      23.00  409664.00

In [18]:
daily_hourly.duplicated().sum()

np.int64(0)